pipeline
  name CenKreChro
  path TiwazCenKreChro
  dtype torch.bfloat16

eval
  num_steps 25
  guidance_scale 1
  protocol fmeuler{num_steps}-g{guidance_scale}
  num_samples 256
  gen_root {output}{job}
  ref_root baselines{dtype}{model}{protocol}
  control_root benchmarks
  gt_stats_root benchmarksstats
  batch_size_per_gpu 4 #untested
  benchmarks
    - MJHQ

quant
  calib
    batch_size 128
    path datasetstorch.bfloat16CenKreChrofmeuler25-g1qdiffs128
    num_samples 128 #untested
    num_workers 8 #untested 
  
  wgts
    calib_range
      element_batch_size 256
      sample_batch_size 256
      element_size 512
      sample_size -1
      
    low_rank
      sample_batch_size 256
      sample_size -1
      
    skips 
    - embed
    - resblock_shortcut
    - resblock_time_proj
    - transformer_proj_in
    - transformer_proj_out
    - down_sample
    - up_sample
    
  ipts
    calib_range
      element_batch_size 128
      sample_batch_size 32
      element_size 512
      sample_size -1
      
    skips 
    - embed
    - resblock_shortcut
    - resblock_time_proj
    - transformer_proj_in
    - transformer_proj_out
    - transformer_norm
    - transformer_add_norm
    - down_sample
    - up_sample
    
  opts
    calib_range
      element_batch_size 128
      sample_batch_size 32
      element_size 512
      sample_size -1

      
  smooth
    proj
      element_batch_size 256
      sample_batch_size 256
      element_size -1
      sample_size -1
      outputs_device cuda
      
    attn
      sample_batch_size 32
      sample_size -1