00-anime: a chibi astronaut, nm22 minimalist style
01-anime: a pink frog, nm22 minimalist style
02-anime: a girl wearing a flower crown, nm22 anime style
03-anime: a girl wearing a flower crown, nm22 style
04-anime: a cute creature, nm22 style
05-anime: a cat with a tiny sword, nm22 illustration style
06-anime: a girl with brown-blonde hair and big round glasses, tired, white tank top,
  jeans, nm22 style
07-anime: a girl with brown-blonde hair and big round glasses, tired, white tank top,
  jeans, nm22 illustration style
08-anime: girl, neck tuft, white hair, sheep horns, blue eyes, nm22 style
09-anime: a boy in a sailor suit frowning, nm22 illustration style
10-anime: girl, neck tuft, white hair, sheep horns, blue eyes, nm22 style
11-anime: a little witch, nm22 minimalist style, pastelcore
12-anime: a chibi astronaut, nm22 minimalist anime style, crayon style
13-anime: a dog wearing a wizard hat, nm22 anime style
14-anime: a girl with wings, nm22 illustration style
15-anime: a robot with a heart on its chest, nm22 style
16-anime: a dancing mushroom, nm22 anime style
17-anime: a knight in a rainbow-colored armor, nm22 style
18-anime: a sleepy cat on a pillow, nm22 pastelcore style
19-anime: a bunny reading a book, nm22 minimalist style
20-anime: a little girl holding a balloon, nm22 crayon style
21-anime: a boy wearing a hoodie and headphones, nm22 lofi style
22-anime: a dragon flying in the night sky, nm22 style
23-anime: a fox wearing glasses, nm22 illustration style
24-anime: a cat sleeping in a hammock, nm22 minimalist style
25-anime: a deer in a forest at night, nm22 anime style
26-anime: a robot watering plants, nm22 style
27-anime: a girl with a magic staff, nm22 anime style
28-anime: a girl riding a bicycle, nm22 minimalist style
29-anime: a frog playing the guitar, nm22 pastelcore style
30-anime: a squirrel eating a nut, nm22 style
31-anime: a penguin with a scarf, nm22 anime style
32-anime: a bird sitting on a branch, nm22 minimalist style
33-anime: a bear wearing a jacket, nm22 illustration style
34-anime: a boy playing the piano, nm22 lofi style
35-anime: a mouse holding a flower, nm22 pastelcore style
36-anime: a cat sitting in a teacup, nm22 style
37-anime: a girl with pink hair and headphones, nm22 anime style
38-anime: a dog wearing sunglasses, nm22 minimalist style
39-anime: a raccoon with a backpack, nm22 illustration style
40-anime: a girl standing under a tree, nm22 lofi style
41-anime: a fish swimming in a bowl, nm22 pastelcore style
42-anime: a girl wearing a cloak, nm22 anime style
43-anime: a bear holding a cup of coffee, nm22 minimalist style
44-anime: a rabbit wearing a crown, nm22 illustration style
45-anime: a fox curled up sleeping, nm22 lofi style
46-anime: a girl sitting on a cloud, nm22 pastelcore style
47-anime: a dog holding a balloon, nm22 style
48-anime: a boy with wings, nm22 anime style
49-anime: a cat playing with yarn, nm22 minimalist style
50-anime: a dragon blowing bubbles, nm22 illustration style
51-anime: a girl sitting on the moon, nm22 lofi style
52-anime: a panda eating bamboo, nm22 pastelcore style
53-anime: a lion wearing glasses, nm22 anime style
54-anime: a girl dancing in the rain, nm22 minimalist style
55-anime: a girl in a witch's hat, nm22 illustration style
56-anime: a bunny riding a bicycle, nm22 pastelcore style
57-anime: a bear holding an umbrella, nm22 style
58-anime: a fox with a scarf, nm22 anime style
59-anime: a cat chasing a butterfly, nm22 minimalist style
60-anime: a boy with a skateboard, nm22 lofi style
61-anime: a girl with braids, nm22 pastelcore style
62-anime: a giraffe with a long scarf, nm22 style
63-anime: a cat wearing a wizard's hat, nm22 anime style
64-anime: a squirrel holding a nut, nm22 minimalist style
65-anime: a dragon with a crown, nm22 illustration style
66-anime: a girl holding a lantern, nm22 lofi style
67-anime: a bunny in a field of flowers, nm22 pastelcore style
68-anime: a cat in space, nm22 style
69-anime: a girl with short hair, nm22 anime style
70-anime: a dog sitting by a campfire, nm22 minimalist style
71-anime: a robot playing chess, nm22 illustration style
72-anime: a girl looking out the window, nm22 lofi style
73-anime: a rabbit holding a cupcake, nm22 pastelcore style
74-anime: a fish swimming in a pond, nm22 style
75-anime: a boy reading a book, nm22 anime style
76-anime: a bear wearing a hat, nm22 minimalist style
77-anime: a cat playing the piano, nm22 illustration style
78-anime: a girl sitting by a river, nm22 lofi style
79-anime: a fox holding a flower, nm22 pastelcore style
80-anime: a dog running in a field, nm22 style
81-anime: a bird flying in the sky, nm22 anime style
82-anime: a girl holding a teddy bear, nm22 minimalist style
83-anime: a mouse with a piece of cheese, nm22 illustration style
84-anime: a girl riding a dragon, nm22 lofi style
85-anime: a frog sitting on a lily pad, nm22 pastelcore style
86-anime: a lion with a crown, nm22 style
87-anime: a boy with a cape, nm22 anime style
88-anime: a penguin sliding on ice, nm22 minimalist style
89-anime: a squirrel with a tiny backpack, nm22 illustration style
90-anime: a girl sitting under a tree, nm22 lofi style
91-anime: a cat chasing a butterfly, nm22 pastelcore style
92-anime: a dragon flying over a city, nm22 style
93-anime: a boy holding a kite, nm22 anime style
94-anime: a dog sitting by a fire, nm22 minimalist style
95-anime: a girl with long flowing hair, nm22 illustration style
96-anime: a boy with a magic wand, nm22 lofi style
97-anime: a cat wearing glasses, nm22 pastelcore style
98-anime: a bear holding a balloon, nm22 style
99-anime: a girl looking at the stars, nm22 anime style
