00-realism: a man in armor with a beard and a sword
01-realism: A handsome man in a suit, 25 years old, cool, futuristic
02-realism: A girl in a suit covered with bold tattoos and holding a vest pistol,
  beautiful woman, 25 years old, cool, future fantasy, turquoise & light orange ping
  curl hair
03-realism: A rugged cowboy in a wide-brimmed hat, holding a rifle, standing in a
  desert at sunset
04-realism: A scientist in a white lab coat examining a holographic display, futuristic
  lab environment
05-realism: A knight with a glowing sword riding a white horse in a medieval battlefield,
  dust in the air
06-realism: A young woman wearing a cyberpunk outfit with neon lights reflecting on
  her, urban cityscape at night
07-realism: An astronaut floating in deep space, Earth in the background, helmet reflecting
  distant stars
08-realism: A warrior princess holding a spear, standing on a cliff overlooking a
  vast ocean
09-realism: A male detective in a trench coat, standing in a rainy alleyway with neon
  signs illuminating the surroundings
10-realism: A futuristic robot holding a plasma rifle, standing in front of a burning
  city
11-realism: A samurai in full armor, sword drawn, standing in a bamboo forest during
  autumn
12-realism: A woman wearing a futuristic exoskeleton suit, preparing for battle in
  a high-tech bunker
13-realism: A pirate captain with a hook hand, standing at the helm of a ship during
  a storm
14-realism: A young boy holding a wooden sword, exploring a magical forest with glowing
  mushrooms
15-realism: An elderly wizard casting a spell with a glowing staff in a stone tower
  filled with books
16-realism: A female assassin with a hooded cloak, leaping across rooftops in a moonlit
  city
17-realism: A giant mech suit piloted by a young soldier, walking through a war-torn
  city
18-realism: A knight fighting a fire-breathing dragon in front of a medieval castle,
  flames and smoke
19-realism: A post-apocalyptic survivor wearing makeshift armor, scavenging for supplies
  in a desolate wasteland
20-realism: A superhero flying over a futuristic city skyline at dusk, cape trailing
  behind
21-realism: A medieval archer aiming a bow at a distant target, standing in a green
  forest clearing
22-realism: A woman in a flowing red dress dancing under a full moon on the beach
23-realism: A cybernetic soldier holding dual pistols, standing in a neon-lit futuristic
  city street
24-realism: A male warrior with tribal tattoos holding a glowing axe, standing in
  front of a waterfall
25-realism: A female pilot in a sleek spacefighter cockpit, preparing for takeoff
  from a space station
26-realism: A steampunk inventor working on a mechanical bird, surrounded by gears
  and blueprints
27-realism: A sorceress with glowing eyes, summoning fire in her hands, standing in
  a dark cave
28-realism: A Viking warrior holding a large shield and axe, standing on a snowy battlefield
29-realism: A futuristic hacker wearing a virtual reality headset, interacting with
  holographic data streams
30-realism: A futuristic cityscape with flying cars, neon lights, and towering skyscrapers
  at sunset
31-realism: A knight in shining armor kneeling before a queen on a golden throne,
  royal court scene
32-realism: A female space explorer walking on the surface of an alien planet with
  strange rock formations
33-realism: A ninja in black garb, jumping through the air with a katana drawn, cherry
  blossoms in the background
34-realism: A male rockstar with long hair playing an electric guitar on a stage with
  a cheering crowd
35-realism: A medieval blacksmith hammering a sword on an anvil, sparks flying in
  a dimly lit forge
36-realism: A futuristic spaceship flying through an asteroid field, dodging incoming
  debris
37-realism: A samurai meditating on a wooden deck overlooking a serene garden pond
  with koi fish
38-realism: A pirate ship battling a naval fleet on the high seas, cannon fire and
  explosions
39-realism: A female warrior in golden armor wielding a spear, leading an army in
  a large battlefield
40-realism: A fantasy elf archer wearing green armor, standing in a mystical forest
  with glowing plants
41-realism: A space marine holding a plasma rifle, standing on the surface of a desolate
  moon with craters
42-realism: A young wizard apprentice studying a glowing ancient book in a library
  with floating candles
43-realism: A cyberpunk biker riding a neon-lit motorcycle through a rainy city street
  at night
44-realism: A male gladiator in a Roman arena, fighting a wild beast with a trident
  and net
45-realism: A female secret agent in a sleek black suit, holding a silenced pistol,
  standing in a high-rise building
46-realism: A futuristic racing car speeding through a neon-lit tunnel at night
47-realism: A male soldier in camouflage gear, crouched in a jungle, aiming a sniper
  rifle
48-realism: A battle-hardened female warrior with scars, holding a massive war hammer
  in a post-apocalyptic wasteland
49-realism: A robotic android walking through a dystopian city, people staring in
  awe
50-realism: A young prince in royal robes, standing in a grand hall with stained glass
  windows
51-realism: A female bounty hunter with a plasma blaster, tracking her target in a
  bustling alien marketplace
52-realism: A male samurai warrior performing a ritual in a traditional Japanese temple
53-realism: A futuristic drone flying through a dense jungle, scanning the area with
  a laser grid
54-realism: A male wizard with a long white beard casting a lightning spell in the
  middle of a storm
55-realism: A futuristic skyscraper with glass walls, towering above a sprawling city
  below
56-realism: A medieval king standing on a balcony overlooking his kingdom, wearing
  a golden crown
57-realism: A female vampire with glowing red eyes, standing in front of a Gothic
  castle under a blood moon
58-realism: A futuristic police officer in power armor, patrolling the streets of
  a cyberpunk city
59-realism: A gladiator holding a sword and shield, standing victorious in a Roman
  arena with cheering crowds
60-realism: A young woman with long flowing hair, standing on a mountain peak at dawn,
  overlooking a misty valley
61-realism: A male firefighter in full gear, rescuing a child from a burning building
62-realism: A futuristic train speeding through a city filled with towering skyscrapers
  and neon lights
63-realism: A knight in rusty armor, standing in front of a crumbling castle, holding
  a broken sword
64-realism: A female archer wearing a hooded cloak, aiming an arrow at a distant enemy
  in a dark forest
65-realism: A male pilot flying a fighter jet in a dogfight, with missiles and explosions
  in the sky
66-realism: A cybernetic humanoid, standing in a high-tech lab, with wires and machines
  connected to its body
67-realism: A female martial artist performing a high kick, surrounded by a crowd
  in an underground fight club
68-realism: A futuristic skyscraper with solar panels on every surface, towering over
  a green city filled with plants
69-realism: A male cowboy riding a horse across a vast desert landscape, with mountains
  in the distance
70-realism: A futuristic robot cleaning the streets of a city with sleek, minimalist
  architecture
71-realism: A female astronaut standing on a space station, looking out at a distant
  galaxy
72-realism: A medieval blacksmith working in his forge, hammering a glowing sword
73-realism: A male secret agent in a tuxedo, holding a gun, standing in front of a
  burning building
74-realism: A futuristic racing car with glowing neon lights, speeding down a highway
  at night
75-realism: A cyberpunk hacker surrounded by floating holographic displays, typing
  rapidly on a keyboard
76-realism: A male samurai with a katana, standing in front of a traditional Japanese
  pagoda
77-realism: A futuristic soldier in power armor, standing in front of a war-torn battlefield
78-realism: A female warrior in dragon armor, holding a flaming sword, standing on
  a mountain peak
79-realism: A knight holding a shield and sword, standing in front of a castle under
  siege
80-realism: A cybernetic assassin in a dark alley, holding a silenced pistol, glowing
  red eyes
81-realism: A futuristic city with flying cars, massive holographic billboards, and
  neon lights everywhere
82-realism: A pirate ship sailing through a stormy sea, with lightning striking in
  the distance
83-realism: A samurai meditating in a serene garden, with cherry blossoms falling
  around him
84-realism: A female knight in silver armor, standing on a battlefield at sunrise,
  holding a banner
85-realism: A futuristic spaceship entering a wormhole, surrounded by swirling colors
  and stars
86-realism: A male explorer in a jungle, cutting through dense vegetation with a machete
87-realism: A robot chef preparing a meal in a futuristic kitchen with robotic arms
88-realism: A gladiator fighting a lion in an ancient Roman coliseum
89-realism: A steampunk airship floating over a vast desert landscape with mountains
  in the distance
90-realism: A medieval knight charging into battle on horseback, holding a lance
91-realism: A female superhero flying through the air, cape billowing behind her,
  over a futuristic city
92-realism: A pirate captain standing on the deck of a ship, looking out at the horizon
  with a spyglass
93-realism: A male samurai in full armor, standing on a battlefield with cherry blossoms
  falling around him
94-realism: A futuristic skyscraper with massive solar panels, surrounded by flying
  drones
95-realism: A male gladiator fighting a lion in an ancient Roman coliseum
96-realism: A female vampire standing in front of a Gothic castle, glowing red eyes
97-realism: A pirate ship sailing through a stormy sea with lightning flashing in
  the sky
98-realism: A knight in shining armor, standing in front of a castle under siege
99-realism: A cybernetic assassin in a dark alley, holding a glowing red sword
